// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/home": {
    params: {};
  };
  "/api/mailto-handler": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/terms": {
    params: {};
  };
  "/pricing": {
    params: {};
  };
  "/privacy": {
    params: {};
  };
  "/contributors": {
    params: {};
  };
  "/hr": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/developer": {
    params: {};
  };
  "/mail": {
    params: {};
  };
  "/mail/create": {
    params: {};
  };
  "/mail/compose": {
    params: {};
  };
  "/mail/under-construction/:path": {
    params: {
      "path": string;
    };
  };
  "/mail/:folder": {
    params: {
      "folder": string;
    };
  };
  "/settings": {
    params: {};
  };
  "/settings/appearance": {
    params: {};
  };
  "/settings/connections": {
    params: {};
  };
  "/settings/danger-zone": {
    params: {};
  };
  "/settings/general": {
    params: {};
  };
  "/settings/labels": {
    params: {};
  };
  "/settings/categories": {
    params: {};
  };
  "/settings/notifications": {
    params: {};
  };
  "/settings/privacy": {
    params: {};
  };
  "/settings/security": {
    params: {};
  };
  "/settings/shortcuts": {
    params: {};
  };
  "/settings/*": {
    params: {
      "*": string;
    };
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/home" | "/api/mailto-handler" | "/about" | "/terms" | "/pricing" | "/privacy" | "/contributors" | "/hr" | "/login" | "/developer" | "/mail" | "/mail/create" | "/mail/compose" | "/mail/under-construction/:path" | "/mail/:folder" | "/settings" | "/settings/appearance" | "/settings/connections" | "/settings/danger-zone" | "/settings/general" | "/settings/labels" | "/settings/categories" | "/settings/notifications" | "/settings/privacy" | "/settings/security" | "/settings/shortcuts" | "/settings/*" | "/*";
  };
  "page.tsx": {
    id: "page";
    page: "/";
  };
  "home/page.tsx": {
    id: "home/page";
    page: "/home";
  };
  "mailto-handler.ts": {
    id: "mailto-handler";
    page: "/api/mailto-handler";
  };
  "(full-width)/layout.tsx": {
    id: "(full-width)/layout";
    page: "/about" | "/terms" | "/pricing" | "/privacy" | "/contributors" | "/hr";
  };
  "(full-width)/about.tsx": {
    id: "(full-width)/about";
    page: "/about";
  };
  "(full-width)/terms.tsx": {
    id: "(full-width)/terms";
    page: "/terms";
  };
  "(full-width)/pricing.tsx": {
    id: "(full-width)/pricing";
    page: "/pricing";
  };
  "(full-width)/privacy.tsx": {
    id: "(full-width)/privacy";
    page: "/privacy";
  };
  "(full-width)/contributors.tsx": {
    id: "(full-width)/contributors";
    page: "/contributors";
  };
  "(full-width)/hr.tsx": {
    id: "(full-width)/hr";
    page: "/hr";
  };
  "(auth)/login/page.tsx": {
    id: "(auth)/login/page";
    page: "/login";
  };
  "(routes)/layout.tsx": {
    id: "(routes)/layout";
    page: "/developer" | "/mail" | "/mail/create" | "/mail/compose" | "/mail/under-construction/:path" | "/mail/:folder" | "/settings" | "/settings/appearance" | "/settings/connections" | "/settings/danger-zone" | "/settings/general" | "/settings/labels" | "/settings/categories" | "/settings/notifications" | "/settings/privacy" | "/settings/security" | "/settings/shortcuts" | "/settings/*" | "/*";
  };
  "(routes)/developer/page.tsx": {
    id: "(routes)/developer/page";
    page: "/developer";
  };
  "(routes)/mail/layout.tsx": {
    id: "(routes)/mail/layout";
    page: "/mail" | "/mail/create" | "/mail/compose" | "/mail/under-construction/:path" | "/mail/:folder";
  };
  "(routes)/mail/page.tsx": {
    id: "(routes)/mail/page";
    page: "/mail";
  };
  "(routes)/mail/create/page.tsx": {
    id: "(routes)/mail/create/page";
    page: "/mail/create";
  };
  "(routes)/mail/compose/page.tsx": {
    id: "(routes)/mail/compose/page";
    page: "/mail/compose";
  };
  "(routes)/mail/under-construction/[path]/page.tsx": {
    id: "(routes)/mail/under-construction/[path]/page";
    page: "/mail/under-construction/:path";
  };
  "(routes)/mail/[folder]/page.tsx": {
    id: "(routes)/mail/[folder]/page";
    page: "/mail/:folder";
  };
  "(routes)/settings/layout.tsx": {
    id: "(routes)/settings/layout";
    page: "/settings" | "/settings/appearance" | "/settings/connections" | "/settings/danger-zone" | "/settings/general" | "/settings/labels" | "/settings/categories" | "/settings/notifications" | "/settings/privacy" | "/settings/security" | "/settings/shortcuts" | "/settings/*";
  };
  "(routes)/settings/page.tsx": {
    id: "(routes)/settings/page";
    page: "/settings";
  };
  "(routes)/settings/appearance/page.tsx": {
    id: "(routes)/settings/appearance/page";
    page: "/settings/appearance";
  };
  "(routes)/settings/connections/page.tsx": {
    id: "(routes)/settings/connections/page";
    page: "/settings/connections";
  };
  "(routes)/settings/danger-zone/page.tsx": {
    id: "(routes)/settings/danger-zone/page";
    page: "/settings/danger-zone";
  };
  "(routes)/settings/general/page.tsx": {
    id: "(routes)/settings/general/page";
    page: "/settings/general";
  };
  "(routes)/settings/labels/page.tsx": {
    id: "(routes)/settings/labels/page";
    page: "/settings/labels";
  };
  "(routes)/settings/categories/page.tsx": {
    id: "(routes)/settings/categories/page";
    page: "/settings/categories";
  };
  "(routes)/settings/notifications/page.tsx": {
    id: "(routes)/settings/notifications/page";
    page: "/settings/notifications";
  };
  "(routes)/settings/privacy/page.tsx": {
    id: "(routes)/settings/privacy/page";
    page: "/settings/privacy";
  };
  "(routes)/settings/security/page.tsx": {
    id: "(routes)/settings/security/page";
    page: "/settings/security";
  };
  "(routes)/settings/shortcuts/page.tsx": {
    id: "(routes)/settings/shortcuts/page";
    page: "/settings/shortcuts";
  };
  "(routes)/settings/[...settings]/page.tsx": {
    id: "(routes)/settings/[...settings]/page";
    page: "/settings/*";
  };
  "meta-files/not-found.ts": {
    id: "meta-files/not-found";
    page: "/*";
  };
};